/* quaestio.c - QUAESTIO (instrumenta): bibliotheca selectorum
 * nominatorum in subsellio (parcum 01KXPV9FPK, INTENTIO phase-log
 * 2026-07-31; frustum II).
 *
 * Usus (ex radice repositorii, per ./silva/quaestio.sh):
 *   quaestio                        index bibliothecae cum causis
 *   quaestio <plagula> <nomen> [param=valor ...]
 *                                   executio nominata (extentus
 *                                   selectae-formatus)
 *   quaestio -invariantia [radix]   percursus invariantium:
 *                                   TENET/VIOLATUR, exitus 1 in
 *                                   violatione - OCULI, nulli unco
 *   quaestio -omnibus <nomen> [param=valor ...] [radix]
 *                                   quaestio nominata super arborem
 *                                   totam (ordines compacti)
 *   quaestio -lista <nomen> [param=valor ...]
 *                                   ut -omnibus, sed viae ex stdin
 *                                   (una per lineam - clausurae per
 *                                   scriptum aedile computatae)
 *   quaestio -proba                 porta nativa
 *
 * Exitus: 0 congruentia/TENENT | 1 nulla/VIOLATUR | 2 fractura.
 *
 * Percursus plagulas generatas SALTAT (notae "GENERATUM" aut
 * "Generated by" in primis 512 octetis, aut super tectum
 * mensurae) - quaeque saltatio LOUDE nominatur, numquam tacite
 * (lectio capsula_libri: tectum tacitum = relatio quae mentitur).
 *
 * Extentus/praeparatio capitum ex selecta.c adaptata (consumptor
 * alter; extractio in unitatem communem cum tertio consumptore).
 */
#include "postulata_posix.h"
#include "latina.h"
#include "piscina.h"
#include "xar.h"
#include "chorda.h"
#include "tabula_dispersa.h"
#include "silva_token.h"
#include "silva_nodus.h"
#include "silva_contextus.h"
#include "silva_parsare.h"
#include "silva_quaestio.h"
#include "silva_quaestiones.h"
#include "silva_c89_oraculum.h"
#include "silva_tabulae_c89.h"
#include <stdio.h>
#include <string.h>
#include <dirent.h>   /* instrumentum solum - macOS/POSIX */

hic_manens constans character* VIA_BIBLIOTHECAE =
    "silva/quaestiones.stml";
hic_manens i32 mensura_maxima = 4194304;

/* --------------------------------------------------
 * extentus subiecti (ex selecta.c)
 * -------------------------------------------------- */

nomen structura {
    b32 validus;
    s32 initium;
    s32 finis;
    i32 linea_prima;
    i32 linea_ultima;
} Extentus;

hic_manens Extentus
_extentum_metiri (constans SilvaParsura* parsura,
    constans SilvaNodus* subiectum, Piscina* piscina)
{
    Extentus ext;
    Xar* series = xar_creare(piscina, magnitudo(SilvaValor));
    i32 cursor = ZEPHYRUM;
    i32 k;

    ext.validus = FALSUM;
    ext.initium = ZEPHYRUM;
    ext.finis = ZEPHYRUM;
    ext.linea_prima = ZEPHYRUM;
    ext.linea_ultima = ZEPHYRUM;

    si (series == NIHIL) redde ext;
    per (k = ZEPHYRUM; k < subiectum->numerus_locorum; k++)
    {
        SilvaValor* novus = (SilvaValor*)xar_addere(series);

        si (novus != NIHIL) *novus = subiectum->loci[k];
    }

    dum (cursor < xar_numerus(series))
    {
        SilvaValor v = *(SilvaValor*)xar_obtinere(series, cursor);

        cursor++;

        si (v.genus == SILVA_VALOR_LISTA)
        {
            i32 m;

            per (m = ZEPHYRUM;
                 m < silva_valor_lista_numerus(v); m++)
            {
                SilvaValor* elem = silva_valor_lista_obtinere(v, m);
                SilvaValor* novus;

                si (elem == NIHIL) perge;
                novus = (SilvaValor*)xar_addere(series);
                si (novus != NIHIL) *novus = *elem;
            }
            perge;
        }
        si (v.genus == SILVA_VALOR_TOKEN && v.datum.token != NIHIL)
        {
            SilvaToken* radix_lex = silva_token_radix(v.datum.token);

            si (radix_lex != NIHIL
                && radix_lex->fons_index == parsura->fons_princeps
                && radix_lex->byte_offset >= ZEPHYRUM)
            {
                s32 finis_lex = radix_lex->byte_offset
                    + (s32)radix_lex->longitudo;

                si (!ext.validus
                    || radix_lex->byte_offset < ext.initium)
                {
                    ext.initium = radix_lex->byte_offset;
                    ext.linea_prima = radix_lex->linea;
                }
                si (!ext.validus || finis_lex > ext.finis)
                {
                    ext.finis = finis_lex;
                    ext.linea_ultima = radix_lex->linea;
                }
                ext.validus = VERUM;
            }
            perge;
        }
        si (v.genus != SILVA_VALOR_NODUS || v.datum.nodus == NIHIL)
        {
            perge;
        }
        {
            constans SilvaNodus* nodus = v.datum.nodus;
            i32 m;

            per (m = ZEPHYRUM; m < nodus->numerus_locorum; m++)
            {
                SilvaValor* novus = (SilvaValor*)xar_addere(series);

                si (novus != NIHIL) *novus = nodus->loci[m];
            }
        }
    }
    redde ext;
}

/* --------------------------------------------------
 * praeparatio capitum (ex selecta.c)
 * -------------------------------------------------- */

hic_manens b32
_praetermittendum (constans character* titulus)
{
    redde (strcmp(titulus, "build") == ZEPHYRUM
        || strcmp(titulus, ".git") == ZEPHYRUM
        || strcmp(titulus, "results") == ZEPHYRUM
        || strcmp(titulus, "node_modules") == ZEPHYRUM)
        ? VERUM : FALSUM;
}

hic_manens vacuum
_caput_praebere (SilvaContextus* ctx, Piscina* piscina,
    TabulaDispersa* visa, constans character* via,
    constans character* titulus)
{
    FILE* pl;
    long mensura_l;
    i32 mensura;
    character* textus;
    chorda clavis;

    clavis = chorda_ex_literis(titulus, piscina);
    si (tabula_dispersa_continet(visa, clavis)) redde;

    pl = fopen(via, "rb");
    si (pl == NIHIL) redde;
    fseek(pl, 0L, SEEK_END);
    mensura_l = ftell(pl);
    fseek(pl, 0L, SEEK_SET);
    si (mensura_l < 0L)
    {
        fclose(pl);
        redde;
    }
    mensura = (i32)mensura_l;

    textus = (character*)piscina_allocare(piscina,
        (memoriae_index)(mensura > ZEPHYRUM ? mensura : I));
    si (textus == NIHIL || (mensura > ZEPHYRUM
        && fread(textus, I, (memoriae_index)mensura, pl)
            != (memoriae_index)mensura))
    {
        fclose(pl);
        redde;
    }
    fclose(pl);

    si (silva_contextus_praebere(ctx, titulus, textus, mensura))
    {
        (vacuum)tabula_dispersa_inserere(visa, clavis, NIHIL);
    }
}

hic_manens vacuum
_capita_praeparare (SilvaContextus* ctx, Piscina* piscina,
    TabulaDispersa* visa, constans character* via)
{
    DIR* dir = opendir(via);
    structura dirent* introitus;

    si (dir == NIHIL) redde;
    dum ((introitus = readdir(dir)) != NIHIL)
    {
        character via_plena[1024];
        memoriae_index m;

        si (introitus->d_name[ZEPHYRUM] == '.') perge;
        si (_praetermittendum(introitus->d_name)) perge;
        si (strlen(via) + strlen(introitus->d_name) + II
            >= magnitudo(via_plena))
        {
            perge;
        }
        sprintf(via_plena, "%s/%s", via, introitus->d_name);

        si (introitus->d_type == DT_DIR)
        {
            _capita_praeparare(ctx, piscina, visa, via_plena);
        }
        alioquin
        {
            m = strlen(introitus->d_name);
            si (m >= III && introitus->d_name[m - II] == '.'
                && introitus->d_name[m - I] == 'h')
            {
                _caput_praebere(ctx, piscina, visa, via_plena,
                    introitus->d_name);
            }
        }
    }
    closedir(dir);
}

/* --------------------------------------------------
 * lectio plagulae in piscinam
 * -------------------------------------------------- */

hic_manens i8*
_plagulam_legere (Piscina* piscina, constans character* via,
    i32* mensura_out)
{
    FILE* pl = fopen(via, "rb");
    long mensura_l;
    i32 mensura;
    i8* fons;

    *mensura_out = ZEPHYRUM;
    si (pl == NIHIL) redde NIHIL;
    fseek(pl, 0L, SEEK_END);
    mensura_l = ftell(pl);
    fseek(pl, 0L, SEEK_SET);
    si (mensura_l < 0L)
    {
        fclose(pl);
        redde NIHIL;
    }
    mensura = (i32)mensura_l;
    fons = (i8*)piscina_allocare(piscina,
        (memoriae_index)(mensura > ZEPHYRUM ? mensura : I));
    si (fons == NIHIL || (mensura > ZEPHYRUM
        && fread(fons, I, (memoriae_index)mensura, pl)
            != (memoriae_index)mensura))
    {
        fclose(pl);
        redde NIHIL;
    }
    fclose(pl);
    *mensura_out = mensura;
    redde fons;
}

/* --------------------------------------------------
 * bibliotheca
 * -------------------------------------------------- */

hic_manens SilvaQuaestiones*
_bibliothecam_legere (Piscina* piscina)
{
    i32 mensura;
    i8* textus = _plagulam_legere(piscina, VIA_BIBLIOTHECAE,
        &mensura);
    chorda fons;
    chorda culpa;
    SilvaQuaestiones* bibliotheca;

    si (textus == NIHIL)
    {
        fprintf(stderr, "quaestio: %s non lecta (ex radice"
            " repositorii currendum)\n", VIA_BIBLIOTHECAE);
        redde NIHIL;
    }
    fons.datum = textus;
    fons.mensura = mensura;
    bibliotheca = silva_quaestiones_legere(piscina,
        &SILVA_C89_REGISTRUM, NIHIL, fons, &culpa);
    si (bibliotheca == NIHIL)
    {
        fprintf(stderr, "quaestio: bibliotheca invalida: %.*s\n",
            (integer)culpa.mensura,
            (constans character*)culpa.datum);
        redde NIHIL;
    }
    redde bibliotheca;
}

hic_manens vacuum
_indicem_imprimere (constans SilvaQuaestiones* bibliotheca)
{
    i32 k;
    i32 p;

    per (k = ZEPHYRUM;
        k < silva_quaestiones_numerus(bibliotheca); k++)
    {
        constans SilvaQuaestioNominata* nominata =
            silva_quaestiones_ad_indicem(bibliotheca, k);

        imprimere("%.*s  (%s)",
            (integer)nominata->titulus.mensura,
            (constans character*)nominata->titulus.datum,
            nominata->gradus == (s32)SILVA_QUAESTIONES_INVARIANS
                ? "invarians" : "oculi");
        per (p = ZEPHYRUM;
            p < xar_numerus(nominata->parametra); p++)
        {
            chorda* parametrum =
                (chorda*)xar_obtinere(nominata->parametra, p);

            imprimere(" %.*s=...",
                (integer)parametrum->mensura,
                (constans character*)parametrum->datum);
        }
        imprimere("\n    %.*s\n",
            (integer)nominata->causa.mensura,
            (constans character*)nominata->causa.datum);
    }
}

/* --------------------------------------------------
 * executio super plagulam unam + impressio extentuum
 * -------------------------------------------------- */

hic_manens i32
_congruentias_imprimere (constans SilvaParsura* parsura,
    constans i8* fons, i32 mensura, Xar* resultata,
    Piscina* piscina, constans character* via,
    constans character* praefixum)
{
    i32 congruentia = ZEPHYRUM;
    i32 m;

    per (m = ZEPHYRUM; m < xar_numerus(resultata); m++)
    {
        constans SilvaQuaestioResultatum* r =
            (constans SilvaQuaestioResultatum*)xar_obtinere(
                resultata, m);
        Extentus ext;
        s32 finis_lineae;
        s32 initium;

        si (r == NIHIL || r->nodus == NIHIL) perge;
        ext = _extentum_metiri(parsura, r->nodus, piscina);
        si (!ext.validus) perge;

        initium = ext.initium;
        dum (initium > ZEPHYRUM && fons[initium - I] != (i8)'\n')
        {
            initium--;
        }
        finis_lineae = ext.finis;
        dum (finis_lineae < (s32)mensura
            && fons[finis_lineae] != (i8)'\n')
        {
            finis_lineae++;
        }
        si (finis_lineae < (s32)mensura) finis_lineae++;

        si (praefixum != NIHIL)
        {
            imprimere("%s%s:%u-%u\n", praefixum, via,
                ext.linea_prima, ext.linea_ultima);
        }
        alioquin
        {
            si (congruentia > ZEPHYRUM) imprimere("\n");
            imprimere("[%s:%u-%u]\n", via,
                ext.linea_prima, ext.linea_ultima);
            fwrite(fons + initium, I,
                (memoriae_index)(finis_lineae - initium),
                stdout);
        }
        congruentia++;
    }
    redde congruentia;
}

/* --------------------------------------------------
 * percursus invariantium
 * -------------------------------------------------- */

nomen structura {
    constans SilvaQuaestioNominata* nominata;
    SilvaQuaestio*                  quaestio;
    i32                             violationes;
} InvariansParatus;

nomen structura {
    SilvaContextus* ctx;
    Xar*            invariantia;   /* InvariansParatus (valore);
                                    * NIHIL = modus singulae */
    SilvaQuaestio*  singula;       /* -omnibus/-lista: quaestio una */
    i32             congruentiae;  /* summa singulae */
    i32             plagulae;
    i32             saltatae;
    i32             cautiones;
    b32             fractura;
} Percursus;

/* lineam datam (1-basatam) fontis imprimere (sine novalinea) */
hic_manens vacuum
_lineam_imprimere (constans i8* fons, i32 mensura, i32 linea)
{
    i32 i = ZEPHYRUM;
    i32 currens = I;
    i32 initium;

    dum (i < mensura && currens < linea)
    {
        si (fons[i] == (i8)'\n') currens++;
        i++;
    }
    initium = i;
    dum (i < mensura && fons[i] != (i8)'\n')
    {
        i++;
    }
    imprimere("%.*s", (integer)(i - initium),
        (constans character*)(fons + initium));
}

/* notae generationis in VEXILLO plagulae (primi C octeti)?
 * Tectum arte: nota in commento posteriore (e.g. instrumentum quod
 * notas EMITTIT) plagulam non damnat - mensuratum 2026-07-31:
 * verae omnes <=80, falsa prima @135 (lex scanner-triggeris,
 * firma sexta). */
hic_manens b32
_est_generata (constans i8* fons, i32 mensura)
{
    i32 tectum = mensura < C ? mensura : C;
    i32 i;

    per (i = ZEPHYRUM; i + 12 <= tectum; i++)
    {
        si (memcmp(fons + i, "GENERATUM", 9) == ZEPHYRUM
            || memcmp(fons + i, "Generated by", 12) == ZEPHYRUM)
        {
            redde VERUM;
        }
    }
    redde FALSUM;
}

/* ordines compacti: [praefixum] via:la-lz  linea1 | linea2
 * (lineae binae - stylus domus typum reditus in linea propria
 * ponit, nomen in secunda). Fructus = numerus ordinum. */
hic_manens i32
_ordines_imprimere (constans SilvaParsura* parsura,
    constans i8* fons, i32 mensura, Xar* resultata,
    Piscina* piscina, constans character* via,
    constans character* praefixum)
{
    i32 numerus = ZEPHYRUM;
    i32 m;

    per (m = ZEPHYRUM; m < xar_numerus(resultata); m++)
    {
        constans SilvaQuaestioResultatum* r =
            (constans SilvaQuaestioResultatum*)xar_obtinere(
                resultata, m);
        Extentus ext;

        si (r == NIHIL || r->nodus == NIHIL) perge;
        ext = _extentum_metiri(parsura, r->nodus, piscina);
        si (!ext.validus) perge;
        si (praefixum != NIHIL)
        {
            imprimere("%s", praefixum);
        }
        imprimere("%s:%u-%u  ", via, ext.linea_prima,
            ext.linea_ultima);
        _lineam_imprimere(fons, mensura, (i32)ext.linea_prima);
        si (ext.linea_ultima > ext.linea_prima)
        {
            imprimere(" | ");
            _lineam_imprimere(fons, mensura,
                (i32)ext.linea_prima + I);
        }
        imprimere("\n");
        numerus++;
    }
    redde numerus;
}

hic_manens vacuum
_plagulam_percurrere (Percursus* percursus, constans character* via)
{
    Piscina* piscina = piscina_generare_dynamicum(
        "quaestio_plagula", 33554432);
    i32 mensura;
    i8* fons;
    SilvaParsura* parsura;
    i32 k;

    si (piscina == NIHIL)
    {
        percursus->fractura = VERUM;
        redde;
    }
    fons = _plagulam_legere(piscina, via, &mensura);
    si (fons == NIHIL)
    {
        imprimere("CAUTIO   %s non lecta\n", via);
        percursus->cautiones++;
        piscina_destruere(piscina);
        redde;
    }
    si (_est_generata(fons, mensura))
    {
        imprimere("SALTATA  %s (generata)\n", via);
        percursus->saltatae++;
        piscina_destruere(piscina);
        redde;
    }
    si (mensura > mensura_maxima)
    {
        imprimere("SALTATA  %s (super tectum %.1f MB)\n", via,
            (duplex)mensura / 1048576.0);
        percursus->saltatae++;
        piscina_destruere(piscina);
        redde;
    }
    parsura = silva_c89_parsare_cum_contextu(piscina,
        percursus->ctx, via, (constans character*)fons, mensura,
        NIHIL);
    si (parsura == NIHIL)
    {
        imprimere("CAUTIO   %s sine arbore\n", via);
        percursus->cautiones++;
        piscina_destruere(piscina);
        redde;
    }
    percursus->plagulae++;
    si (percursus->singula != NIHIL)
    {
        Xar* resultata = silva_quaestio_exsequi(percursus->singula,
            parsura->commissio->radix, piscina);

        si (resultata != NIHIL)
        {
            percursus->congruentiae += _ordines_imprimere(parsura,
                fons, mensura, resultata, piscina, via, NIHIL);
        }
        piscina_destruere(piscina);
        redde;
    }
    per (k = ZEPHYRUM; k < xar_numerus(percursus->invariantia); k++)
    {
        InvariansParatus* invarians = (InvariansParatus*)
            xar_obtinere(percursus->invariantia, k);
        Xar* resultata = silva_quaestio_exsequi(invarians->quaestio,
            parsura->commissio->radix, piscina);
        i32 inventae;
        character praefixum[128];

        si (resultata == NIHIL) perge;
        sprintf(praefixum, "VIOLATUR %.*s  ",
            (integer)(invarians->nominata->titulus.mensura < XC
                ? invarians->nominata->titulus.mensura : XC),
            (constans character*)invarians->nominata->titulus.datum);
        inventae = _ordines_imprimere(parsura, fons, mensura,
            resultata, piscina, via, praefixum);
        invarians->violationes += inventae;
    }
    piscina_destruere(piscina);
}

hic_manens vacuum
_arborem_percurrere (Percursus* percursus, constans character* via)
{
    DIR* dir = opendir(via);
    structura dirent* introitus;

    si (dir == NIHIL) redde;
    dum ((introitus = readdir(dir)) != NIHIL)
    {
        character via_plena[1024];
        memoriae_index m;

        si (introitus->d_name[ZEPHYRUM] == '.') perge;
        si (_praetermittendum(introitus->d_name)) perge;
        /* fixa = corpora synthetica (invalida consulto) */
        si (strcmp(introitus->d_name, "fixa") == ZEPHYRUM) perge;
        si (strlen(via) + strlen(introitus->d_name) + II
            >= magnitudo(via_plena))
        {
            perge;
        }
        sprintf(via_plena, "%s/%s", via, introitus->d_name);

        si (introitus->d_type == DT_DIR)
        {
            _arborem_percurrere(percursus, via_plena);
        }
        alioquin
        {
            m = strlen(introitus->d_name);
            si (m >= III && introitus->d_name[m - II] == '.'
                && introitus->d_name[m - I] == 'c')
            {
                _plagulam_percurrere(percursus, via_plena);
            }
        }
    }
    closedir(dir);
}

hic_manens s32
_invariantia_percurrere (constans character* radix)
{
    Piscina* piscina_ctx = piscina_generare_dynamicum(
        "quaestio_ctx", 16777216);
    Piscina* piscina_bib = piscina_generare_dynamicum(
        "quaestio_bib", 8388608);
    SilvaQuaestiones* bibliotheca;
    Percursus percursus;
    i32 k;
    i32 violatae = ZEPHYRUM;

    si (piscina_ctx == NIHIL || piscina_bib == NIHIL) redde II;
    bibliotheca = _bibliothecam_legere(piscina_bib);
    si (bibliotheca == NIHIL) redde II;

    percursus.invariantia = xar_creare(piscina_bib,
        magnitudo(InvariansParatus));
    percursus.singula = NIHIL;
    percursus.congruentiae = ZEPHYRUM;
    percursus.plagulae = ZEPHYRUM;
    percursus.saltatae = ZEPHYRUM;
    percursus.cautiones = ZEPHYRUM;
    percursus.fractura = FALSUM;
    si (percursus.invariantia == NIHIL) redde II;

    per (k = ZEPHYRUM;
        k < silva_quaestiones_numerus(bibliotheca); k++)
    {
        constans SilvaQuaestioNominata* nominata =
            silva_quaestiones_ad_indicem(bibliotheca, k);

        si (nominata->gradus == (s32)SILVA_QUAESTIONES_INVARIANS)
        {
            chorda culpa;
            InvariansParatus* invarians = (InvariansParatus*)
                xar_addere(percursus.invariantia);

            si (invarians == NIHIL) redde II;
            invarians->nominata = nominata;
            invarians->quaestio = silva_quaestiones_parare(
                piscina_bib, bibliotheca, nominata, NIHIL,
                ZEPHYRUM, &culpa);
            invarians->violationes = ZEPHYRUM;
            si (invarians->quaestio == NIHIL)
            {
                fprintf(stderr, "quaestio: %.*s\n",
                    (integer)culpa.mensura,
                    (constans character*)culpa.datum);
                redde II;
            }
        }
    }
    si (xar_numerus(percursus.invariantia) == ZEPHYRUM)
    {
        imprimere("VERDICTUM: NULLA INVARIANTIA (bibliotheca"
            " gradum invarians non fert)\n");
        redde ZEPHYRUM;
    }

    percursus.ctx = silva_contextus_creare(piscina_ctx);
    si (percursus.ctx == NIHIL) redde II;
    {
        TabulaDispersa* visa = tabula_dispersa_creare_chorda(
            piscina_ctx, DXII);

        si (visa == NIHIL) redde II;
        _capita_praeparare(percursus.ctx, piscina_ctx, visa, ".");
    }

    _arborem_percurrere(&percursus, radix);

    imprimere("\n");
    per (k = ZEPHYRUM; k < xar_numerus(percursus.invariantia); k++)
    {
        InvariansParatus* invarians = (InvariansParatus*)
            xar_obtinere(percursus.invariantia, k);

        si (invarians->violationes > ZEPHYRUM)
        {
            violatae++;
        }
        imprimere("INVARIANS %.*s  %s",
            (integer)invarians->nominata->titulus.mensura,
            (constans character*)invarians->nominata->titulus.datum,
            invarians->violationes > ZEPHYRUM
                ? "VIOLATUR" : "TENET");
        si (invarians->violationes > ZEPHYRUM)
        {
            imprimere(" (%ld)", (longus)invarians->violationes);
        }
        imprimere("\n");
    }
    imprimere("VERDICTUM: %s (invariantia %ld, plagulae %ld,"
        " saltatae %ld, cautiones %ld)\n",
        violatae > ZEPHYRUM ? "VIOLATA" : "OMNES TENENT",
        (longus)xar_numerus(percursus.invariantia),
        (longus)percursus.plagulae,
        (longus)percursus.saltatae,
        (longus)percursus.cautiones);
    si (percursus.fractura) redde II;
    redde violatae > ZEPHYRUM ? I : ZEPHYRUM;
}

/* -omnibus / -lista: quaestio nominata UNA super arborem totam aut
 * listam viarum ex stdin (clausurae per scriptum aedile computatae).
 * Ordines compacti; exitus 0 congruentia / 1 nulla / 2 fractura. */
hic_manens s32
_singulam_percurrere (constans character* titulus,
    SilvaQuaestionesArgumentum* argumenta,
    i32 numerus_argumentorum, constans character* radix,
    b32 ex_stdin)
{
    Piscina* piscina_ctx = piscina_generare_dynamicum(
        "quaestio_ctx", 16777216);
    Piscina* piscina_bib = piscina_generare_dynamicum(
        "quaestio_bib", 8388608);
    SilvaQuaestiones* bibliotheca;
    constans SilvaQuaestioNominata* nominata;
    Percursus percursus;
    chorda culpa;

    si (piscina_ctx == NIHIL || piscina_bib == NIHIL) redde II;
    bibliotheca = _bibliothecam_legere(piscina_bib);
    si (bibliotheca == NIHIL) redde II;
    nominata = silva_quaestiones_invenire(bibliotheca, titulus);
    si (nominata == NIHIL)
    {
        fprintf(stderr, "quaestio: nomen ignotum '%s'"
            " (sine argumentis = index)\n", titulus);
        redde II;
    }
    percursus.invariantia = NIHIL;
    percursus.congruentiae = ZEPHYRUM;
    percursus.plagulae = ZEPHYRUM;
    percursus.saltatae = ZEPHYRUM;
    percursus.cautiones = ZEPHYRUM;
    percursus.fractura = FALSUM;
    percursus.singula = silva_quaestiones_parare(piscina_bib,
        bibliotheca, nominata, argumenta, numerus_argumentorum,
        &culpa);
    si (percursus.singula == NIHIL)
    {
        fprintf(stderr, "quaestio: %.*s\n",
            (integer)culpa.mensura,
            (constans character*)culpa.datum);
        redde II;
    }
    percursus.ctx = silva_contextus_creare(piscina_ctx);
    si (percursus.ctx == NIHIL) redde II;
    {
        TabulaDispersa* visa = tabula_dispersa_creare_chorda(
            piscina_ctx, DXII);

        si (visa == NIHIL) redde II;
        _capita_praeparare(percursus.ctx, piscina_ctx, visa, ".");
    }
    si (ex_stdin)
    {
        character linea[1024];

        dum (fgets(linea, (integer)magnitudo(linea), stdin)
            != NIHIL)
        {
            memoriae_index m = strlen(linea);

            dum (m > (memoriae_index)ZEPHYRUM
                && (linea[m - I] == '\n' || linea[m - I] == '\r'
                    || linea[m - I] == ' '))
            {
                linea[m - I] = '\0';
                m--;
            }
            si (m == (memoriae_index)ZEPHYRUM) perge;
            _plagulam_percurrere(&percursus, linea);
        }
    }
    alioquin
    {
        _arborem_percurrere(&percursus, radix);
    }
    imprimere("congruentiae %ld (plagulae %ld, saltatae %ld,"
        " cautiones %ld)\n",
        (longus)percursus.congruentiae,
        (longus)percursus.plagulae,
        (longus)percursus.saltatae,
        (longus)percursus.cautiones);
    si (percursus.fractura) redde II;
    redde percursus.congruentiae > ZEPHYRUM ? ZEPHYRUM : I;
}

/* --------------------------------------------------
 * porta nativa (-proba)
 * -------------------------------------------------- */

hic_manens s32
_proba (vacuum)
{
    Piscina* piscina = piscina_generare_dynamicum("quaestio_proba",
        8388608);
    constans character* fons_stml =
        "<quaestiones>"
        "<quaestio titulus=\"vocantes\" gradus=\"oculi\">"
        "<selector>definitio-functionis:vocat($functio)</selector>"
        "<parametrum titulus=\"functio\"/>"
        "<causa>probatio</causa></quaestio>"
        "<quaestio titulus=\"redde-bis\" gradus=\"invarians\">"
        "<selector>redde redde</selector>"
        "<causa>probatio</causa></quaestio>"
        "</quaestiones>";
    constans character* fons_c =
        "int quadratum(int x) { return x * x; }\n"
        "int bis(int x) { return quadratum(x) + quadratum(x); }\n";
    chorda fons;
    chorda culpa;
    SilvaQuaestiones* bibliotheca;
    constans SilvaQuaestioNominata* nominata;
    SilvaParsura* parsura;
    SilvaQuaestio* quaestio;
    SilvaQuaestionesArgumentum argumenta[I];
    Xar* resultata;
    b32 fracta = FALSUM;

    si (piscina == NIHIL) redde II;
    fons = chorda_ex_literis(fons_stml, piscina);
    bibliotheca = silva_quaestiones_legere(piscina,
        &SILVA_C89_REGISTRUM, NIHIL, fons, &culpa);
    si (bibliotheca == NIHIL
        || silva_quaestiones_numerus(bibliotheca) != II)
    {
        fprintf(stderr, "quaestio -proba: lectio fracta\n");
        piscina_destruere(piscina);
        redde II;
    }
    parsura = silva_c89_parsare(piscina, "proba.c", fons_c,
        (i32)strlen(fons_c), NIHIL);
    si (parsura == NIHIL || !parsura->successus)
    {
        fprintf(stderr, "quaestio -proba: parsura fracta\n");
        piscina_destruere(piscina);
        redde II;
    }
    nominata = silva_quaestiones_invenire(bibliotheca, "vocantes");
    argumenta[ZEPHYRUM].titulus = chorda_ex_literis("functio",
        piscina);
    argumenta[ZEPHYRUM].valor = chorda_ex_literis("quadratum",
        piscina);
    quaestio = silva_quaestiones_parare(piscina, bibliotheca,
        nominata, argumenta, I, &culpa);
    si (quaestio == NIHIL)
    {
        fprintf(stderr, "quaestio -proba: parare fractum\n");
        fracta = VERUM;
    }
    alioquin
    {
        resultata = silva_quaestio_exsequi(quaestio,
            parsura->commissio->radix, piscina);
        si (resultata == NIHIL || xar_numerus(resultata) != I)
        {
            fprintf(stderr, "quaestio -proba: numerus falsus\n");
            fracta = VERUM;
        }
    }
    /* invarians: zero congruentiae in fonte innocenti */
    nominata = silva_quaestiones_invenire(bibliotheca, "redde-bis");
    quaestio = silva_quaestiones_parare(piscina, bibliotheca,
        nominata, NIHIL, ZEPHYRUM, &culpa);
    si (quaestio == NIHIL)
    {
        fracta = VERUM;
    }
    alioquin
    {
        resultata = silva_quaestio_exsequi(quaestio,
            parsura->commissio->radix, piscina);
        si (resultata == NIHIL
            || xar_numerus(resultata) != ZEPHYRUM)
        {
            fprintf(stderr, "quaestio -proba: invarians falsus\n");
            fracta = VERUM;
        }
    }
    piscina_destruere(piscina);
    si (fracta) redde II;
    imprimere("QUAESTIO PROBA TENET\n");
    redde ZEPHYRUM;
}

/* --------------------------------------------------
 * principale
 * -------------------------------------------------- */

s32 principale (integer argc, character** argv)
{
    constans character* via = NIHIL;
    constans character* titulus = NIHIL;
    SilvaQuaestionesArgumentum argumenta[XXXII];
    i32 numerus_argumentorum = ZEPHYRUM;
    Piscina* piscina_ctx;
    Piscina* piscina;
    SilvaContextus* ctx;
    SilvaQuaestiones* bibliotheca;
    constans SilvaQuaestioNominata* nominata;
    SilvaQuaestio* quaestio;
    chorda culpa;
    i8* fons;
    i32 mensura;
    SilvaParsura* parsura;
    Xar* resultata;
    i32 congruentia;
    integer k;

    /* modi speciales primum */
    si (argc >= II && strcmp(argv[I], "-proba") == ZEPHYRUM)
    {
        redde _proba();
    }
    si (argc >= II && strcmp(argv[I], "-invariantia") == ZEPHYRUM)
    {
        redde _invariantia_percurrere(argc >= III ? argv[II] : ".");
    }
    si (argc >= III && (strcmp(argv[I], "-omnibus") == ZEPHYRUM
        || strcmp(argv[I], "-lista") == ZEPHYRUM))
    {
        b32 est_lista = strcmp(argv[I], "-lista") == ZEPHYRUM
            ? VERUM : FALSUM;
        SilvaQuaestionesArgumentum series[XXXII];
        i32 numerus_seriei = ZEPHYRUM;
        constans character* radix = ".";
        Piscina* piscina_arg = piscina_generare_dynamicum(
            "quaestio_arg", 1048576);

        si (piscina_arg == NIHIL) redde II;
        per (k = III; k < argc; k++)
        {
            constans character* aequale = strchr(argv[k], '=');

            si (aequale != NIHIL && aequale != argv[k])
            {
                chorda titulus_argumenti;

                si (numerus_seriei >= (i32)XXXII)
                {
                    fprintf(stderr, "quaestio: argumenta nimia"
                        " (tectum XXXII)\n");
                    redde II;
                }
                titulus_argumenti.datum = (i8*)piscina_allocare(
                    piscina_arg,
                    (memoriae_index)(aequale - argv[k] > 0L
                        ? (memoriae_index)(aequale - argv[k])
                        : (memoriae_index)I));
                si (titulus_argumenti.datum == NIHIL) redde II;
                memcpy(titulus_argumenti.datum, argv[k],
                    (size_t)(aequale - argv[k]));
                titulus_argumenti.mensura =
                    (i32)(aequale - argv[k]);
                series[numerus_seriei].titulus = titulus_argumenti;
                series[numerus_seriei].valor = chorda_ex_literis(
                    aequale + I, piscina_arg);
                numerus_seriei++;
            }
            alioquin si (!est_lista)
            {
                radix = argv[k];
            }
            alioquin
            {
                fprintf(stderr, "quaestio -lista: argumentum"
                    " ignotum %s (viae ex stdin veniunt)\n",
                    argv[k]);
                redde II;
            }
        }
        redde _singulam_percurrere(argv[II], series,
            numerus_seriei, radix, est_lista);
    }

    piscina = piscina_generare_dynamicum("quaestio", 33554432);
    si (piscina == NIHIL)
    {
        fprintf(stderr, "quaestio: piscina deest\n");
        redde II;
    }

    /* sine argumentis: index bibliothecae */
    si (argc == I)
    {
        bibliotheca = _bibliothecam_legere(piscina);
        si (bibliotheca == NIHIL) redde II;
        _indicem_imprimere(bibliotheca);
        redde ZEPHYRUM;
    }

    /* executio nominata: <plagula> <nomen> [param=valor ...] */
    per (k = I; k < argc; k++)
    {
        constans character* aequale = strchr(argv[k], '=');

        si (strcmp(argv[k], "-omnia") == ZEPHYRUM)
        {
            mensura_maxima = ZEPHYRUM;
        }
        alioquin si (aequale != NIHIL && aequale != argv[k])
        {
            SilvaQuaestionesArgumentum* argumentum;
            chorda titulus_argumenti;

            si (numerus_argumentorum >= (i32)XXXII)
            {
                fprintf(stderr, "quaestio: argumenta nimia"
                    " (tectum XXXII)\n");
                redde II;
            }
            argumentum = &argumenta[numerus_argumentorum];
            numerus_argumentorum++;
            titulus_argumenti.datum = (i8*)piscina_allocare(
                piscina,
                (memoriae_index)(aequale - argv[k] > 0L
                    ? (memoriae_index)(aequale - argv[k])
                    : (memoriae_index)I));
            si (titulus_argumenti.datum == NIHIL) redde II;
            memcpy(titulus_argumenti.datum, argv[k],
                (size_t)(aequale - argv[k]));
            titulus_argumenti.mensura = (i32)(aequale - argv[k]);
            argumentum->titulus = titulus_argumenti;
            argumentum->valor = chorda_ex_literis(aequale + I,
                piscina);
        }
        alioquin si (via == NIHIL)
        {
            via = argv[k];
        }
        alioquin si (titulus == NIHIL)
        {
            titulus = argv[k];
        }
        alioquin
        {
            fprintf(stderr, "quaestio: argumentum ignotum %s\n",
                argv[k]);
            redde II;
        }
    }
    si (via == NIHIL || titulus == NIHIL)
    {
        fprintf(stderr, "usus: quaestio [<plagula> <nomen>"
            " [param=valor ...]] | -invariantia [radix] | -proba"
            "  (ex radice repositorii)\n");
        redde II;
    }

    bibliotheca = _bibliothecam_legere(piscina);
    si (bibliotheca == NIHIL) redde II;
    nominata = silva_quaestiones_invenire(bibliotheca, titulus);
    si (nominata == NIHIL)
    {
        fprintf(stderr, "quaestio: nomen ignotum '%s'"
            " (sine argumentis = index)\n", titulus);
        redde II;
    }
    quaestio = silva_quaestiones_parare(piscina, bibliotheca,
        nominata, argumenta, numerus_argumentorum, &culpa);
    si (quaestio == NIHIL)
    {
        fprintf(stderr, "quaestio: %.*s\n",
            (integer)culpa.mensura,
            (constans character*)culpa.datum);
        redde II;
    }

    piscina_ctx = piscina_generare_dynamicum("quaestio_ctx",
        16777216);
    si (piscina_ctx == NIHIL) redde II;
    ctx = silva_contextus_creare(piscina_ctx);
    si (ctx == NIHIL) redde II;
    si (mensura_maxima == ZEPHYRUM)
    {
        ctx->fines.lexemata = ZEPHYRUM;
    }
    {
        TabulaDispersa* visa = tabula_dispersa_creare_chorda(
            piscina_ctx, DXII);

        si (visa == NIHIL) redde II;
        _capita_praeparare(ctx, piscina_ctx, visa, ".");
    }

    fons = _plagulam_legere(piscina, via, &mensura);
    si (fons == NIHIL)
    {
        fprintf(stderr, "quaestio: plagula non lecta: %s\n", via);
        redde II;
    }
    si (mensura_maxima > ZEPHYRUM && mensura > mensura_maxima)
    {
        fprintf(stderr, "quaestio: plagula super tectum %.1f MB"
            " (-omnia tollit)\n", (duplex)mensura / 1048576.0);
        redde II;
    }
    parsura = silva_c89_parsare_cum_contextu(piscina, ctx, via,
        (constans character*)fons, mensura, NIHIL);
    si (parsura == NIHIL)
    {
        fprintf(stderr, "quaestio: sine arbore: %s\n", via);
        redde II;
    }
    si (!parsura->successus)
    {
        fprintf(stderr, "quaestio CAUTIO: arbor cum erroribus"
            " (%ld) in %s\n", (longus)parsura->numerus_errorum,
            via);
    }
    resultata = silva_quaestio_exsequi(quaestio,
        parsura->commissio->radix, piscina);
    si (resultata == NIHIL)
    {
        fprintf(stderr, "quaestio: exsecutio fracta\n");
        redde II;
    }
    congruentia = _congruentias_imprimere(parsura, fons, mensura,
        resultata, piscina, via, NIHIL);
    redde congruentia > ZEPHYRUM ? ZEPHYRUM : I;
}
