# musivum_fontes_generata.sh - GENERATUM AB AEDILE - NE MANU EDITES
# regeneratio: ./tools/fontes_generare.sh tessera/musivum_fontes_generata.sh tessera/instrumenta/principalia/musivum.c tessera/instrumenta/musivum/musivum_pictura.c tessera/fontes/tessera_cellula.c tessera/fontes/tessera_eventum.c tessera/fontes/tessera_opus.c tessera/fontes/tessera_pons_memoriae.c tessera/fontes/tessera_pons_posix.c
declare -a RADIX_FONTES=(
    "chorda"
    "chorda_aedificator"
    "color"
    "componens"
    "delineare"
    "delineare_mandata"
    "fenestra_textus"
    "figura"
    "filum"
    "fons"
    "friatio"
    "imago"
    "imago_opus"
    "internamentum"
    "mandatum"
    "modulus"
    "piscina"
    "quadrans"
    "runae"
    "runae_tabulae"
    "selectio"
    "series_terminalis"
    "stml"
    "tabula_dispersa"
    "tessellatio"
    "thema"
    "utf8"
    "xar"
)
