/* capsula_libri.h - Generated by capsula_generare */

#ifndef CAPSULA_libri_H
#define CAPSULA_libri_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_libri;

#endif /* CAPSULA_libri_H */
