/* capsula_forum.h - Generated by capsula_generare */

#ifndef CAPSULA_forum_H
#define CAPSULA_forum_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_forum;

#endif /* CAPSULA_forum_H */
