/* capsula_assets.h - Generated by capsula_generare */

#ifndef CAPSULA_assets_H
#define CAPSULA_assets_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_assets;

#endif /* CAPSULA_assets_H */
