/* capsula_hospes.h - Generated by capsula_generare */

#ifndef CAPSULA_hospes_H
#define CAPSULA_hospes_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_hospes;

#endif /* CAPSULA_hospes_H */
