/* capsula_mensor.h - Generated by capsula_generare */

#ifndef CAPSULA_mensor_H
#define CAPSULA_mensor_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_mensor;

#endif /* CAPSULA_mensor_H */
