/* capsula_tabella.h - Generated by capsula_generare */

#ifndef CAPSULA_tabella_H
#define CAPSULA_tabella_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_tabella;

#endif /* CAPSULA_tabella_H */
