/* lexicon_c89.c - Descriptor lexicalis C89 pro materia
 *
 * GENERATUM per materia/instrumenta/lexicon_c89_generare.sh.
 * NOLI MANU EMENDARE - fontes sunt silva_token.h (enumeratio) et
 * silva_arbor.c (ORTHOGRAPHIAE).
 *
 * SEDES TEMPORARIA. Hic descriptor ad frontem C89 pertinet, quae
 * in silva vivit; in probationibus materiae vivit dum phasis I
 * currit, quia vehiculum portae est (shim C89 -> materia). Phasis
 * V eum in silvam movet. Materia ipsa lingua CARERE debet (M8).
 */

#include "lexicon_c89.h"

hic_manens constans MateriaLexGenus GENERA_C89[] = {
    { "EOF",                       "",                    MATERIA_LEX_FIXUM,        MATERIA_MUNUS_FINIS },
    { "OCTETUS_IGNOTUS",           NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_SUBSTANTIVUM },
    { "STRING_IMPERFECTUM",        NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_SUBSTANTIVUM },
    { "CHARACTER_IMPERFECTUM",     NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_SUBSTANTIVUM },
    { "IDENTIFICATOR",             NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_SUBSTANTIVUM },
    { "INTEGER",                   NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_SUBSTANTIVUM },
    { "FLOAT",                     NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_SUBSTANTIVUM },
    { "CHARACTER_LIT",             NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_SUBSTANTIVUM },
    { "STRING_LIT",                NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_SUBSTANTIVUM },
    { "AUTO",                      "auto",                MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "BREAK",                     "break",               MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "CASE",                      "case",                MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "CHAR",                      "char",                MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "CONST",                     "const",               MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "CONTINUE",                  "continue",            MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "DEFAULT",                   "default",             MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "DO",                        "do",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "DOUBLE",                    "double",              MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "ELSE",                      "else",                MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "ENUM",                      "enum",                MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "EXTERN",                    "extern",              MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "FLOAT_KW",                  "float",               MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "FOR",                       "for",                 MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "GOTO",                      "goto",                MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "IF",                        "if",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "INT",                       "int",                 MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "LONG",                      "long",                MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "REGISTER",                  "register",            MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "RETURN",                    "return",              MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SHORT",                     "short",               MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SIGNED",                    "signed",              MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SIZEOF",                    "sizeof",              MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "STATIC",                    "static",              MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "STRUCT",                    "struct",              MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SWITCH",                    "switch",              MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "TYPEDEF",                   "typedef",             MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "UNION",                     "union",               MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "UNSIGNED",                  "unsigned",            MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "VOID",                      "void",                MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "VOLATILE",                  "volatile",            MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "WHILE",                     "while",               MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "QUADRA_APERTA",             "[",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "QUADRA_CLAUSA",             "]",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "PAREN_APERTA",              "(",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "PAREN_CLAUSA",              ")",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "BRACE_APERTA",              "{",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "BRACE_CLAUSA",              "}",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "PUNCTUM",                   ".",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SAGITTA",                   "->",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "INCREMENTUM",               "++",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "DECREMENTUM",               "--",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "AMPERSAND",                 "&",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "STAR",                      "*",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "PLUS",                      "+",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "MINUS",                     "-",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "TILDE",                     "~",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "EXCLAMATIO",                "!",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SOLIDUS",                   "/",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "PERCENTUM",                 "%",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SINISTRORSUM",              "<<",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "DEXTRORSUM",                ">>",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "MINOR",                     "<",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "MAIOR",                     ">",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "MINOR_AEQUALIS",            "<=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "MAIOR_AEQUALIS",            ">=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "AEQUALIS_AEQUALIS",         "==",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "NON_AEQUALIS",              "!=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "CARET",                     "^",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "BARRA",                     "|",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "ET_ET",                     "&&",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "VEL_VEL",                   "||",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "QUAESTIO",                  "?",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "COLON",                     ":",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SEMICOLON",                 ";",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "ELLIPSIS",                  "...",                 MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "ASSIGNATIO",                "=",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "STAR_ASSIGNATIO",           "*=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SOLIDUS_ASSIGNATIO",        "/=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "PERCENTUM_ASSIGNATIO",      "%=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "PLUS_ASSIGNATIO",           "+=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "MINUS_ASSIGNATIO",          "-=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SINISTRORSUM_ASSIGNATIO",   "<<=",                 MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "DEXTRORSUM_ASSIGNATIO",     ">>=",                 MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "AMPERSAND_ASSIGNATIO",      "&=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "CARET_ASSIGNATIO",          "^=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "BARRA_ASSIGNATIO",          "|=",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "COMMA",                     ",",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "CANCELLUM",                 "#",                   MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "CANCELLUM_CANCELLUM",       "##",                  MATERIA_LEX_FIXUM,        MATERIA_MUNUS_SUBSTANTIVUM },
    { "SPATIA",                    " ",                   MATERIA_LEX_REPETITUM,    MATERIA_MUNUS_SPATIUM },
    { "TABULAE",                   "\t",                  MATERIA_LEX_REPETITUM,    MATERIA_MUNUS_SPATIUM },
    { "NOVA_LINEA",                "\n",                  MATERIA_LEX_TERMINATOR,   MATERIA_MUNUS_LINEA },
    { "CONTINUATIO",               "\\\n",                MATERIA_LEX_TERMINATOR,   MATERIA_MUNUS_LAMINA },
    { "COMMENTUM_CLAUSUM",         NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_COMMENTUM },
    { "COMMENTUM_LINEA",           NIHIL,                 MATERIA_LEX_VERBATIM,     MATERIA_MUNUS_COMMENTUM },
};

constans MateriaLexiconCoctum LEXICON_C89 = {
    GENERA_C89,
    (i32)(magnitudo(GENERA_C89) / magnitudo(GENERA_C89[0])),
    "lex-",
    (s32)LEXICON_C89_GENUS_SPATIA
};
