/* lexicon_c89.h - Indices generum lexicalium C89
 *
 * GENERATUM per materia/instrumenta/lexicon_c89_generare.sh.
 * NOLI MANU EMENDARE.
 *
 * Ordo enumerationis ordinem SilvaLexemaGenus EXACTE sequitur -
 * id est quod shim phasis I gratis reddit: index unus utrimque
 * idem genus nominat, ergo conversione non opus est.
 */

#ifndef LEXICON_C89_H
#define LEXICON_C89_H

#include "materia_lexicon.h"

nomen enumeratio {
    LEXICON_C89_GENUS_EOF = 0,
    LEXICON_C89_GENUS_OCTETUS_IGNOTUS,
    LEXICON_C89_GENUS_STRING_IMPERFECTUM,
    LEXICON_C89_GENUS_CHARACTER_IMPERFECTUM,
    LEXICON_C89_GENUS_IDENTIFICATOR,
    LEXICON_C89_GENUS_INTEGER,
    LEXICON_C89_GENUS_FLOAT,
    LEXICON_C89_GENUS_CHARACTER_LIT,
    LEXICON_C89_GENUS_STRING_LIT,
    LEXICON_C89_GENUS_AUTO,
    LEXICON_C89_GENUS_BREAK,
    LEXICON_C89_GENUS_CASE,
    LEXICON_C89_GENUS_CHAR,
    LEXICON_C89_GENUS_CONST,
    LEXICON_C89_GENUS_CONTINUE,
    LEXICON_C89_GENUS_DEFAULT,
    LEXICON_C89_GENUS_DO,
    LEXICON_C89_GENUS_DOUBLE,
    LEXICON_C89_GENUS_ELSE,
    LEXICON_C89_GENUS_ENUM,
    LEXICON_C89_GENUS_EXTERN,
    LEXICON_C89_GENUS_FLOAT_KW,
    LEXICON_C89_GENUS_FOR,
    LEXICON_C89_GENUS_GOTO,
    LEXICON_C89_GENUS_IF,
    LEXICON_C89_GENUS_INT,
    LEXICON_C89_GENUS_LONG,
    LEXICON_C89_GENUS_REGISTER,
    LEXICON_C89_GENUS_RETURN,
    LEXICON_C89_GENUS_SHORT,
    LEXICON_C89_GENUS_SIGNED,
    LEXICON_C89_GENUS_SIZEOF,
    LEXICON_C89_GENUS_STATIC,
    LEXICON_C89_GENUS_STRUCT,
    LEXICON_C89_GENUS_SWITCH,
    LEXICON_C89_GENUS_TYPEDEF,
    LEXICON_C89_GENUS_UNION,
    LEXICON_C89_GENUS_UNSIGNED,
    LEXICON_C89_GENUS_VOID,
    LEXICON_C89_GENUS_VOLATILE,
    LEXICON_C89_GENUS_WHILE,
    LEXICON_C89_GENUS_QUADRA_APERTA,
    LEXICON_C89_GENUS_QUADRA_CLAUSA,
    LEXICON_C89_GENUS_PAREN_APERTA,
    LEXICON_C89_GENUS_PAREN_CLAUSA,
    LEXICON_C89_GENUS_BRACE_APERTA,
    LEXICON_C89_GENUS_BRACE_CLAUSA,
    LEXICON_C89_GENUS_PUNCTUM,
    LEXICON_C89_GENUS_SAGITTA,
    LEXICON_C89_GENUS_INCREMENTUM,
    LEXICON_C89_GENUS_DECREMENTUM,
    LEXICON_C89_GENUS_AMPERSAND,
    LEXICON_C89_GENUS_STAR,
    LEXICON_C89_GENUS_PLUS,
    LEXICON_C89_GENUS_MINUS,
    LEXICON_C89_GENUS_TILDE,
    LEXICON_C89_GENUS_EXCLAMATIO,
    LEXICON_C89_GENUS_SOLIDUS,
    LEXICON_C89_GENUS_PERCENTUM,
    LEXICON_C89_GENUS_SINISTRORSUM,
    LEXICON_C89_GENUS_DEXTRORSUM,
    LEXICON_C89_GENUS_MINOR,
    LEXICON_C89_GENUS_MAIOR,
    LEXICON_C89_GENUS_MINOR_AEQUALIS,
    LEXICON_C89_GENUS_MAIOR_AEQUALIS,
    LEXICON_C89_GENUS_AEQUALIS_AEQUALIS,
    LEXICON_C89_GENUS_NON_AEQUALIS,
    LEXICON_C89_GENUS_CARET,
    LEXICON_C89_GENUS_BARRA,
    LEXICON_C89_GENUS_ET_ET,
    LEXICON_C89_GENUS_VEL_VEL,
    LEXICON_C89_GENUS_QUAESTIO,
    LEXICON_C89_GENUS_COLON,
    LEXICON_C89_GENUS_SEMICOLON,
    LEXICON_C89_GENUS_ELLIPSIS,
    LEXICON_C89_GENUS_ASSIGNATIO,
    LEXICON_C89_GENUS_STAR_ASSIGNATIO,
    LEXICON_C89_GENUS_SOLIDUS_ASSIGNATIO,
    LEXICON_C89_GENUS_PERCENTUM_ASSIGNATIO,
    LEXICON_C89_GENUS_PLUS_ASSIGNATIO,
    LEXICON_C89_GENUS_MINUS_ASSIGNATIO,
    LEXICON_C89_GENUS_SINISTRORSUM_ASSIGNATIO,
    LEXICON_C89_GENUS_DEXTRORSUM_ASSIGNATIO,
    LEXICON_C89_GENUS_AMPERSAND_ASSIGNATIO,
    LEXICON_C89_GENUS_CARET_ASSIGNATIO,
    LEXICON_C89_GENUS_BARRA_ASSIGNATIO,
    LEXICON_C89_GENUS_COMMA,
    LEXICON_C89_GENUS_CANCELLUM,
    LEXICON_C89_GENUS_CANCELLUM_CANCELLUM,
    LEXICON_C89_GENUS_SPATIA,
    LEXICON_C89_GENUS_TABULAE,
    LEXICON_C89_GENUS_NOVA_LINEA,
    LEXICON_C89_GENUS_CONTINUATIO,
    LEXICON_C89_GENUS_COMMENTUM_CLAUSUM,
    LEXICON_C89_GENUS_COMMENTUM_LINEA,

    LEXICON_C89_NUMERUS_GENERUM
} LexiconC89Genus;

externus constans MateriaLexiconCoctum LEXICON_C89;

#endif /* LEXICON_C89_H */
