/* capsula_villa.h - Generated by capsula_generare */

#ifndef CAPSULA_villa_H
#define CAPSULA_villa_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_villa;

#endif /* CAPSULA_villa_H */
