/* capsula_templates.h - Generated by capsula_generare */

#ifndef CAPSULA_templates_H
#define CAPSULA_templates_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_templates;

#endif /* CAPSULA_templates_H */
