/* capsula_silex_frons.h - Generated by capsula_generare */

#ifndef CAPSULA_silex_frons_H
#define CAPSULA_silex_frons_H

#include "capsula.h"

externus constans CapsulaEmbed capsula_silex_frons;

#endif /* CAPSULA_silex_frons_H */
